services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.26
    container_name: openhands
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.26-nikolaik
      - LOG_ALL_EVENTS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/appdata/openhands:/.openhands-state
      - /home/anand:/data/anand
    ports:
      - "3010:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    pull_policy: if_not_present