services:
  # Airsonic Advanced - Music Server
  airsonic-advanced:
    image: lscr.io/linuxserver/airsonic-advanced
    container_name: airsonic-advanced
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - default
    volumes:
      - $DOCKERDIR/appdata/airsonic-advanced/podcasts:/data/podcasts
      - $DOCKERDIR/appdata/airsonic-advanced/playlists:/data/playlists
      - $DOCKERDIR/appdata/airsonic-advanced/config:/config
      - $MEDIADIR1/music:/data/music
      # - $MEDIADIR3:/data/media3
    ports:
      - "$AIRSONICADVANCED_PORT:4040"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      JAVA_OPTS: '-Dserver.forward-headers-strategy=native' # optional - if you use a reverse-proxy
    # DOCKER-LABELS-PLACEHOLDER