services:
  # PostgreSQL - Database fpr Teslamate
  pgsql-teslamate:
    container_name: pgsql-teslamate
    image: postgres:16-alpine
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    #   start_period: 20s
    #   interval: 30s
    #   retries: 5
    #   timeout: 5s
    networks:
      - default
    ports:
      - "$PGSQLTESLAMATE_PORT:5432"
    volumes:
      - $DOCKERDIR/appdata/pgsql-teslamate:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=teslamate
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgsql_teslamate_passwd
    secrets:
      - pgsql_teslamate_passwd