services:
  # Firefly III - Personal Finance Manager
  firefly:
    image: fireflyiii/core:latest
    container_name: firefly
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$FIREFLY_PORT:8080"
    volumes:
      - $DOCKERDIR/appdata/firefly:/var/www/html/storage/upload
    env_file: $DOCKERDIR/appdata/firefly/firefly.env
    # DOCKER-LABELS-PLACEHOLDER
