services:
  # MakeMKV - Video Editing (Ripping from Disks)
  makemkv:
    image: jlesage/makemkv:latest
    container_name: makemkv
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["media","all"]
    networks:
      - default
    ports:
      - "$MAKEMKV_PORT:5800"
    volumes:
      - $DOWNLOADSDIR:/data/downloads
      - $DOCKERDIR/appdata/makemkv/config:/config
      - /dev/shm:/dev/shm
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      UMASK: 002
      TZ: $TZ
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      # VNC_PASSWORD: $MAKEMKV_VNC_PASSWD
    # DOCKER-LABELS-PLACEHOLDER
